# Generated by Django 4.1.3 on 2024-10-25 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0003_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='ankur', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
